[package]
name = "rustoner"
version = "0.1.0"
authors = ["hatellezp <hatellezp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rustoner_shiq"
path = "src/main_shiq.rs"

[[bin]]
name = "tester"
path = "src/test.rs"

# this is the good one
[[bin]]
name = "rustoner_dllite"
path = "src/main_dl_lite.rs"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
structopt = { version = "0.3", features = ["paw"] }
paw = "1.0"
rusqlite = "*"
exitcode = "*"
question = "0.2.2"
quick-xml = { version = "0.22.0", features = ["serialize"] }